// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC40cZsYqNdbo56pI-EpuQ07c0BbntUXHM',
    appId: '1:692160740877:web:36355d5f83b76dd3a7df44',
    messagingSenderId: '692160740877',
    projectId: 'flutter-starter-230fe',
    authDomain: 'flutter-starter-230fe.firebaseapp.com',
    storageBucket: 'flutter-starter-230fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhMzgKu12yCXXu9ni5WOPKSai39C3WhTE',
    appId: '1:692160740877:android:8352c47e6e46ed8aa7df44',
    messagingSenderId: '692160740877',
    projectId: 'flutter-starter-230fe',
    storageBucket: 'flutter-starter-230fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_dok7ow7iMvEoUfxYdjCyBcVItlbk_t8',
    appId: '1:692160740877:ios:a6bf9987048a7cbca7df44',
    messagingSenderId: '692160740877',
    projectId: 'flutter-starter-230fe',
    storageBucket: 'flutter-starter-230fe.appspot.com',
    iosBundleId: 'com.example.firebaseexample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_dok7ow7iMvEoUfxYdjCyBcVItlbk_t8',
    appId: '1:692160740877:ios:c39de3f29dc397c3a7df44',
    messagingSenderId: '692160740877',
    projectId: 'flutter-starter-230fe',
    storageBucket: 'flutter-starter-230fe.appspot.com',
    iosBundleId: 'com.example.firebaseexample.RunnerTests',
  );
}
